# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Kl < Formula
  desc ""
  homepage "https://github.com/klyall/kl-cli"
  version "0.2.2"
  license "Apache"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/klyall/kl-cli/releases/download/v0.2.2/kl_0.2.2_Darwin_arm64.tar.gz", :using => CurlDownloadStrategy
      sha256 "d5f15d8d83997e0739b7a52806fc8131361f20d6e41452a3675b9ffae220122e"

      def install
        bin.install "kl"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/klyall/kl-cli/releases/download/v0.2.2/kl_0.2.2_Darwin_x86_64.tar.gz", :using => CurlDownloadStrategy
      sha256 "c2705ff6ac4563ba41614dcd093d0c920228164fb2dcd928342910291ef9acd0"

      def install
        bin.install "kl"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/klyall/kl-cli/releases/download/v0.2.2/kl_0.2.2_Linux_arm64.tar.gz", :using => CurlDownloadStrategy
      sha256 "b5c22fc2d917783e825236c51632aab326747193c4980f51a6ac6a78d7e61715"

      def install
        bin.install "kl"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/klyall/kl-cli/releases/download/v0.2.2/kl_0.2.2_Linux_x86_64.tar.gz", :using => CurlDownloadStrategy
      sha256 "8823f01ffe0646afb481acbbe654579fe8fa97e2b91cc17f2153d45856210af7"

      def install
        bin.install "kl"
      end
    end
  end
end
